// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoSlSwzCfD809BDWaAXwQHATP82lsBsGk',
    appId: '1:421232313367:web:ec2441653f3fd3f06fc852',
    messagingSenderId: '421232313367',
    projectId: 'smart-study-app-8f459',
    authDomain: 'smart-study-app-8f459.firebaseapp.com',
    storageBucket: 'smart-study-app-8f459.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASHI1fjuwvjhP07gi0NNWE6GNYa4TOSdk',
    appId: '1:421232313367:android:f7d9789257bd1d5f6fc852',
    messagingSenderId: '421232313367',
    projectId: 'smart-study-app-8f459',
    storageBucket: 'smart-study-app-8f459.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx5b6uVxdU-4_4BXTQLoiQT-qZCDRZZmc',
    appId: '1:421232313367:ios:fc1ef6b43bb1bdf56fc852',
    messagingSenderId: '421232313367',
    projectId: 'smart-study-app-8f459',
    storageBucket: 'smart-study-app-8f459.firebasestorage.app',
    iosBundleId: 'com.example.smartStudyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx5b6uVxdU-4_4BXTQLoiQT-qZCDRZZmc',
    appId: '1:421232313367:ios:fc1ef6b43bb1bdf56fc852',
    messagingSenderId: '421232313367',
    projectId: 'smart-study-app-8f459',
    storageBucket: 'smart-study-app-8f459.firebasestorage.app',
    iosBundleId: 'com.example.smartStudyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoSlSwzCfD809BDWaAXwQHATP82lsBsGk',
    appId: '1:421232313367:web:bfc7fcb4d52eeab46fc852',
    messagingSenderId: '421232313367',
    projectId: 'smart-study-app-8f459',
    authDomain: 'smart-study-app-8f459.firebaseapp.com',
    storageBucket: 'smart-study-app-8f459.firebasestorage.app',
  );
}
